// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy9fMrsT_3Irt5KtWWfC5kZNQLwySXwEU',
    appId: '1:304473496524:web:37224949fe479db0449b69',
    messagingSenderId: '304473496524',
    projectId: 'recipesapp-fbbc5',
    authDomain: 'recipesapp-fbbc5.firebaseapp.com',
    storageBucket: 'recipesapp-fbbc5.firebasestorage.app',
    measurementId: 'G-TG7XGM2KFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXkrTwQJruyw9E_op1tjqJQmM0wnGduDo',
    appId: '1:304473496524:android:f473a3ccd4553272449b69',
    messagingSenderId: '304473496524',
    projectId: 'recipesapp-fbbc5',
    storageBucket: 'recipesapp-fbbc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2HgOglVcx8_juuc_6mTLJpI7EaqKAe0g',
    appId: '1:304473496524:ios:14eeee51ad58fd08449b69',
    messagingSenderId: '304473496524',
    projectId: 'recipesapp-fbbc5',
    storageBucket: 'recipesapp-fbbc5.firebasestorage.app',
    iosBundleId: 'com.example.recipesBookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2HgOglVcx8_juuc_6mTLJpI7EaqKAe0g',
    appId: '1:304473496524:ios:14eeee51ad58fd08449b69',
    messagingSenderId: '304473496524',
    projectId: 'recipesapp-fbbc5',
    storageBucket: 'recipesapp-fbbc5.firebasestorage.app',
    iosBundleId: 'com.example.recipesBookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy9fMrsT_3Irt5KtWWfC5kZNQLwySXwEU',
    appId: '1:304473496524:web:4f23aba5afc2871f449b69',
    messagingSenderId: '304473496524',
    projectId: 'recipesapp-fbbc5',
    authDomain: 'recipesapp-fbbc5.firebaseapp.com',
    storageBucket: 'recipesapp-fbbc5.firebasestorage.app',
    measurementId: 'G-QV57N9BDJJ',
  );
}
